### ISSUE TITLE
게시글 삭제 BE

### ISSUE THREAD

**Issue by new-h2** [modueui-jaeneung/modu-repo#14]
## TODO
- [x] 리스트에서 글작성 버튼 생성 -  글작성페이지 연결
- [x] 상세페이지에서 수정버튼생성 - 수정페이지 연결
- [x] 상세페이지에서 삭제버튼생성 - 삭제BE 완료

## 코멘트
[DB]
Post 테이블 Columns 수정
  >price int(20) 추가
  >postStatus : 3 일 경우 게시글 삭제 상태추가 (0.거래가능, 1.예약, 2.거래완료, 3.삭제)
삭제된 게시글은 리스트페이지에 나오지않게 처리
