### ISSUE TITLE
게시글 작성BE

### ISSUE THREAD

**Issue by new-h2** [modueui-jaeneung/modu-repo#15]
## TODO
- [x] 글작성BE  
- [x] 에디터툴위에 이미지 업로드 후 인서트 되는지, 상세페이지에 나오는지 확인
- [x] Date 타입, datetime_local format 확인
- [x] datetime-local 로 캘린더로 날짜,시간 입력 받기 추가
- [x] price 최소금액, 최고금액 적용
- [x] 취소버튼 클릭시 리스트페이지 이동
## 추가작업
- [ ] 작성자 이름,주소,자기소개 post DB추가 및 신청에도 적용하기
- [ ] 게시글 + 신청  연동하기 
- [ ] 지도

## 코멘트
[DB]
Post 테이블 Columns 수정
  > post_id AUTO_INCREMENT 추가
   start_time varchar(50) 
   end_time varchar(50)  
- date -> String 타입으로 변경
 > content varchar(16000) 
- 에디터툴위로 마크다운으로 이미지와 html적용된 텍스트가 저장되어서 큰 용량의 데이터타입이 필요함
