### ISSUE TITLE
채팅 서버 API

### ISSUE THREAD

**Issue by hgk9872** [modueui-jaeneung/modu-repo#6]
## Description
채팅 서버 구현

## Todo
* [x]  API 명세서 작성
* [x]  Swagger 문서 추가
* [x]  stomp 프로토콜 웹소켓 설정 작업
* [x]  채팅 이력 저장 기능 추가
* [x]  채팅 기능 테스트용 화면 설계
* [x]  채팅방 생성 API
* [x]  채팅방 조회 API
* [x]  채팅방 리스트 조회 API
* [x]  외부 메시지 브로커
* [x]  stomp client의 통신 상태 로그 출력
* [ ]  인증/인가 로직 추가

## ETC
- 채팅 이력 저장 데이터베이스 : MongoDB
- 외부 메시지 브로커 : Redis
